/**
 * @description 
 * @class dny.VendingMachine.ChangeMoneyBagModel
 * @names dny.VendingMachine
 * @namespace
 * @author 
 * @version 1.0.0
 * @since February 13, 2012
 * @copyright Copyright (c) 2012, NHN Technology Services inc.
 * @generated by Jindo2 Code Generator v1.0.3
 */
dny.VendingMachine.ChangeMoneyBagModel = jindo.$Class({
	/** @lends dny.VendingMachine.ChangeMoneyBagModel.prototype */

	/**
     * @description Cash entity.
	 * @private
	 * @type Wrapping Array of Wrapping Object
	 */
	_wawoCashEntity : null,

	/**
     * @description $init.
	 * @public
	 * @constructs
	 */
	$init : function() {
		this._wawoCashEntity = new jindo.$A();
	},

	/**
     * @description Fill cash for change.
	 * @public
	 * @param {Wrapping Object} woCash
	 * @param {Number} nCount
	 */
	fillCashForChange : function(woCash, nCount) {
		for(var i=0; i<nCount; i++){
			this._wawoCashEntity.push(woCash);
		}
	},

	/**
     * @description Return cash.
	 * @public
	 * @param {Number} nMoney
	 * @returns {Wrapping Array of Wrapping Object}
	 */
	returnCash : function(nMoney) {
		var _wawoCashEntity = new jindo.$A();
		while(nMoney > 0){
			if(nMoney >= 1000){
				_wawoCashEntity.push(new dny.VendingMachine.CashEntity(1000, true));
				nMoney = nMoney - 1000;
			}else if(nMoney >= 500){
				_wawoCashEntity.push(new dny.VendingMachine.CashEntity(500, false));
				nMoney = nMoney - 500;
			}else if(nMoney >= 100){
				_wawoCashEntity.push(new dny.VendingMachine.CashEntity(100, false));
				nMoney = nMoney - 100;
			}else if(nMoney >= 50){
				_wawoCashEntity.push(new dny.VendingMachine.CashEntity(50, false));
				nMoney = nMoney - 50;
			}
		}
		return _wawoCashEntity;
	},

	/**
     * @description Is empty?
	 * @public
	 * @returns {Boolean}
	 */
	isEmpty : function() {
		return (this._wawoCashEntity.length() == 0) ? true : false;
	}

});

