/**
 * @description 
 * @class dny.VendingMachine.BeverageEntity
 * @names dny.VendingMachine
 * @namespace
 * @author 
 * @version 1.0.0
 * @since February 13, 2012
 * @copyright Copyright (c) 2012, NHN Technology Services inc.
 * @generated by Jindo2 Code Generator v1.0.3
 */
dny.VendingMachine.BeverageEntity = jindo.$Class({
	/** @lends dny.VendingMachine.BeverageEntity.prototype */

	/**
     * @description Name.
	 * @private
	 * @type String
	 */
	_sName : null,

	/**
     * @description $init.
	 * @public
	 * @constructs
	 * @param {String} sName
	 */
	$init : function(sName) {
		this._sName = sName;
	},

	/**
     * @description Get name.
	 * @public
	 */
	getName : function() {
		return this._sName;
	}

});

