/**
 * @description 
 * @class dny.VendingMachine.CashEntity
 * @names dny.VendingMachine
 * @namespace
 * @author 
 * @version 1.0.0
 * @since February 13, 2012
 * @copyright Copyright (c) 2012, NHN Technology Services inc.
 * @generated by Jindo2 Code Generator v1.0.3
 */
dny.VendingMachine.CashEntity = jindo.$Class({
	/** @lends dny.VendingMachine.CashEntity.prototype */

	/**
     * @description Value.
	 * @private
	 * @type Number
	 */
	_nValue : null,
	/**
     * @description Paper money.
	 * @private
	 * @type Boolean
	 */
	_bPaperMoney : null,

	/**
     * @description $init.
	 * @public
	 * @constructs
	 * @param {Number} nValue
	 * @param {Boolean} bPaperMoney
	 */
	$init : function(nValue, bPaperMoney) {
		this._nValue = nValue;
		this._bPaperMoney = bPaperMoney;
	},

	/**
     * @description Get value.
	 * @public
	 * @return {Number}
	 */
	getValue : function() {
		return this._nValue;
	},

	/**
     * @description Is paper money?
	 * @public
	 * @return {Boolean}
	 */
	isPaperMoney : function() {
		return this._bPaperMoney;
	}

});

