/**
 * @description 
 * @class dny.VendingMachine.EarnedMoneyBagModel
 * @names dny.VendingMachine
 * @namespace
 * @author 
 * @version 1.0.0
 * @since February 13, 2012
 * @copyright Copyright (c) 2012, NHN Technology Services inc.
 * @generated by Jindo2 Code Generator v1.0.3
 */
dny.VendingMachine.EarnedMoneyBagModel = jindo.$Class({
	/** @lends dny.VendingMachine.EarnedMoneyBagModel.prototype */

	/**
     * @description Cash entity.
	 * @private
	 * @type Wrapping Array of Wrapping Object
	 */
	_wawoCashEntity : null,

	/**
     * @description $init.
	 * @public
	 * @constructs
	 */
	$init : function() {
		this._wawoCashEntity = new jindo.$A();
	},

	/**
     * @description Earn cash.
	 * @public
	 * @param {Wrapping Array of Wrapping Object} wawoCashEntity
	 */
	earnCash : function(wawoCashEntity) {
		for(var i=0; i<wawoCashEntity.length(); i++){
			this._wawoCashEntity.push(wawoCashEntity.get(i));
		}
	},

	/**
     * @description Withdraw earned cash.
	 * @public
	 * @returns {Wrapping Array of Wrapping Object}
	 */
	withdrawEarnedCash : function() {
		var _wawoEarnedCashEntity = new jindo.$A();
		for(var i=0; i<this._wawoCashEntity.length(); i++){
			_wawoEarnedCashEntity.push(this._wawoCashEntity.get(i));
		}
		this._wawoCashEntity.empty();
		return _wawoEarnedCashEntity;
	}

});

